def recommend_hairstyle(face_shape):
    recommendations = {
        "Oval": [
            "Textured Pixie",
            "Curly Side Part",
            "Butterfly Haircut",
            "Soft Blowout",
            "Mermaid Waves",
            "Side-Swept Pixie",
            "Grown-Out Pixie",
            "Polished Pixie",
            "Structured Undercut",
            "Natural Pompadour",
            "Voluminous Pompadour",
            "Chin-Length Bob",
            "Side-Parted Lob",
            "Textured Bob With Heavy Bangs",
            "Wet-Look Bob",
            "Shoulder-Length Shag",
            "Angled Lob",
            "Blunt French Bob",
            "Layered Bob",
            "Heart-Shaped Fro",
            "Asymmetrical Bob",
            "Blunt Bob",
            "'80s Lob With Bangs",
            "Modern Shag",
            "Soft Curls",
            "Modern Mullet",
            "Shoulder-Length Loose Waves",
            "Half-Up, Half-Down Lob",
            "Curtain Bangs",
            "Retro Waves",
            "Wavy Shag With Bangs",
            "Shoulder-Length Soft Curls",
            "Deep Side Part",
            "Face-Framing Layers",
            "Long and Wavy",
            "Side-Swept Bangs",
            "Beachy Face-Framing Layers",
            "Long and Sleek",
            "Long, Tight Waves With Center Part",
            "Side-Parted Retro Waves",
            "Half-Up, Half-Down Topknot",
            "Air-Dried Waves With Volume",
            "Long Single Braid",
            "Updo With Wavy Tendrils",
            "Long Double Braids",
            "Updo with Cascading Curtain Bangs",
            "Natural Half-Up, Half-Down",
            "Center-Parted Topknot",
            "Low Braid with Layers",
            "Full Fringe",
            "Center-Parted Curls",
            "Casual Toussle",
            "Sleek and Center-Parted",
            "Subtle Side-Swept",
            "Slick-Back Ponytail",
            "Runway-Ready Waves"
        ],
        "Round": [
            "Shaggy with thin bangs",
            "Wavy bob",
            "Natural layer",
            "Korean Pixie Cut",
            "Layered mid-length",
            "Layered bob with curtain bangs",
            "Shaggy layered bob with bangs",
            "Flowing long layers with bangs",
            "Sleek blunt bob with curtain bangs",
            "Slimming medium tousled",
            "Crinkled Lob",
            "Old Hollywood Waves",
            "Textured Lob With Feathery Fringe",
            "Long Blunt Waves",
            "Sleek Lob",
            "Smooth, Barely-There Waves",
            "Long, Wavy Layers With Boosted Side Bangs",
            "The Ultimate Blowout",
            "Close Crop",
            "Glam Mermaid Waves",
            "Rounded Bob With Deep Side Part",
            "Retro Bob With Deep Side Part",
            "Piecey Pixie",
            "Bouncy Lob",
            "Ballerina Bun With Curtain Bangs",
            "Undone Messy Bun",
            "Curtain Bangs",
            "Straight Tresses",
            "Loose Updo",
            "Center Parted Tousled Lob",
            "Asymmetric Bob",
            "Blunt, Shoulder Length Waves",
            "Split Half-Up, Half-Down",
            "Modern Mullet",
            "Blunt Bangs",
            "Razored French Fringe",
            "Bouncy, Mid-Length Layers",
            "Long Layers",
            "Side-Swept Waves"
        ],
        "Square": [
            "Curtain Bangs",
            "Curly and Short",
            "French Bob",
            "Wavy Lob",
            "Epic Length With Dramatic Side Part",
            "Italian Bob",
            "Curtain Layers",
            "Rounded Bob",
            "Tousled Bob",
            "Feathered Shoulder-Length Cut",
            "Razor-Cut Lob",
            "Textured Layers",
            "Long Length and Side-Swept Bangs",
            "Long, Voluminous Layers",
            "Mid-Length Cut With Bangs",
            "Spiraled Bob",
            "Choppy Pixie",
            "Baby Bangs",
            "Face-Framing Angles",
            "Silky and Sideswept",
            "A Weightless Cut",
            "Sleek, Mono-Length Cut",
            "Curly Layers",
            "Modern Shag",
            "Sideswept Blowout",
            "Curly Shag",
            "Soft Structure",
            "Cropped Curls",
            "Timeless Pageboy",
            "Braided Updo",
        ],
        "Heart": [
            "Close Crop With Baby Bangs",
            "Short and Choppy Pixie",
            "Curly Pixie",
            "Long and Side-Parted Pixie",
            "Sculpted Pixie",
            "Slicked-Back Bun",
            "Waved Bixie",
            "Bent Midi Bob",
            "Retro Glam",
            "Tousled Tendril Half-Updo",
            "Cropped and Stacked",
            "Flared Bob",
            "Curly Lob With Bangs",
            "Collarbone-Length with Layers",
            "Wavy Shoulder Length with Side Bangs",
            "Wavy Lob with a Center Part",
            "Fluffy Curls",
            "Pulled Back with a Deep Side Part",
            "Flipped-Out Lob With a Center Part",
            "Flipped-In Lob",
            "Wavy Lob With a Side Part",
            "Long Layers and Beach Waves",
            "Tight Topknot",
            "Shaved Pixie Cut",
            "Long Wavy Layers With a Side Part",
            "Loose Waves With Long Layers and a Center Part",
            "Natural Curls",
            "Wavy Layers With a Deep Side Part",
            "Face-Framing Highlights and Long Layers",
            "Long Feathered Layers",
            "Long and Textured Bangs",
            "Blunt Bangs",
            "Long and Wispy Bangs",
            "Curtain Bangs",
            "Side-Swept Bangs",
        ],
        "Oblong": [
            "Curly Shag",
            "Center Parted Ponytail",
            "Piecy Pixie",
            "Curtain Bangs",
            "Blunt Bangs",
            "Curly Ponytail",
            "Perfectly Messy Bun",
            "Angled Bob",
            "French Bob",
            "Sculpted Curls",
            "Teased Curls",
            "Half-Up, Half-Down",
            "Long Layers With Short Angles",
            "Blunt Bob With Bangs",
            "Middle-Parted Waves",
            "Bouncy Bob",
            "Layered Lob",
            "Shoulder Length Finger Waves",
            "Asymmetric Lob With Bangs",
            "Long, Tousled Layers",
            "Bouncy Blowout",
            "Full Curls",
            "Beachy Waves",
            "Updo With Bangs",
            "Weightless Waves",
            "Close Cropped Pixie",
            "Center Parted Tousled Lob",
            "Long, Retro Waves",
            "Pineapple Updo",
            "Faux Curtain Bangs",
            "Modern Pageboy",
            "Classic Braid",
            "Jellyfish Cut",
            "Textured Length",
            "Center-Parted Waves"
        ]
    }
    return recommendations.get(face_shape, [])
